spring:
  application:
    name: library

  datasource:
    driver-class-name:  org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres

  flyway:
    default-schema: library
    baseline-on-migrate: true
    clean-disabled: true
